export const YEAR_AWARDED_OPTIONS = [
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
  "2025",
] as const;

export const SCHOLARSHIP_OPTIONS = [
  "UG RA 7687",
  "UG Merit",
  "JLSS RA 7687",
  "JLSS Merit",
  "JLSS RA 10612",
] as const;

// University Dropdown Options (based on CHED list and regional coverage for DOST scholars)
export const UNIVERSITY_OPTIONS = [
  // NCR - Manila & Metro Manila
  "Adamson University",
  "Ateneo de Manila University",
  "Centro Escolar University",
  "De La Salle University – Manila",
  "Eulogio Rodriguez Institute of Science and Technology",
  "Far Eastern University – Manila",
  "Far Eastern University – Tech",
  "Far Eastern University – NRMF",
  "Mapúa University (Manila/Makati)",
  "National University – Manila",
  "New Era University",
  "Our Lady of Fatima University – Quezon City",
  "Our Lady of Fatima University – Valenzuela",
  "Philippine Normal University",
  "National Aviation Academy of the Philippines",
  "Polytechnic University of the Philippines – Manila",
  "Polytechnic University of the Philippines – Taguig",
  "Polytechnic University of the Philippines – Quezon City",
  "Pamantasan ng Lungsod ng Maynila",
  "Rizal Technological University – Mandaluyong",
  "Rizal Technological University – Pasig",
  "Technological Institute of the Philippines – Manila",
  "Technological Institute of the Philippines – Quezon City",
  "Technological University of the Philippines – Manila",
  "Technological University of the Philippines – Taguig",
  "Trinity University of Asia",
  "Marikina Polytechnic College",
  "Assumption College San Lorenzo",
  "PATTS College of Aeronautics",
  "Manila Central University (MCU)",
  "University of Santo Tomas",
  "University of the East – Manila",
  "University of the Philippines – Diliman",
  "University of the Philippines – Manila",
  "University of the Philippines",
  // Calabarzon (Batangas, Cavite, Laguna, Rizal, Quezon)
  "Batangas State University",
  "Cavite State University",
  "Laguna State Polytechnic University",
  "University of Rizal System",
  "University of Batangas",
  "Lyceum of the Philippines University – Batangas",
  "De La Salle Lipa",
  "Southern Luzon State University",
  "Manuel S. Enverga University Foundation",
  "First Asia Institute of Technology and Humanities",
  "University of the Philippines Los Baños",
  // Central Luzon
  "Central Luzon State University",
  "Bulacan State University",
  "Tarlac State University",
  "Don Honorio Ventura Technological State University",
  "Nueva Ecija University of Science and Technology",
  "Bataan Peninsula State University",
  "Pampanga State University",
  "Angeles University Foundation",
  "Holy Angel University",
  "University of the Assumption",
  // Bicol Region
  "Bicol University",
  "Ateneo de Naga University",
  "University of Nueva Caceres",
  "Polytechnic State University of Bicol",
  "Central Bicol State University of Agriculture",
  // Ilocos & Cagayan Valley
  "Mariano Marcos State University",
  "Pangasinan State University",
  "Cagayan State University",
  "Isabela State University",
  "University of Northern Philippines",
  "Nueva Vizcaya State University",
  // Cordillera
  "University of the Philippines Baguio",
  "Saint Louis University",
  "University of the Cordilleras",
  "Benguet State University",
  "University of Baguio",
  // Western Visayas (Iloilo, Bacolod, etc.)
  "University of the Philippines Visayas",
  "West Visayas State University",
  "Central Philippine University",
  "University of San Agustin",
  "University of Iloilo",
  "University of Saint La Salle",
  "Carlos Hilado Memorial State University",
  "Capiz State University",
  "Aklan State University",
  // Central Visayas (Cebu, Bohol, Dumaguete) - KickSTART Visayas venue
  "University of Southern Philippines Foundation",
  "University of San Carlos",
  "Cebu Technological University",
  "Cebu Normal University",
  "Silliman University",
  "University of Cebu",
  "Cebu Doctor's University",
  "University of the Visayas",
  "Holy Name University",
  "Bohol Island State University",
  "Negros Oriental State University",
  // Eastern Visayas
  "Eastern Visayas State University",
  "Leyte Normal University",
  "University of the Philippines Tacloban",
  "Visayas State University",
  "Samar State University",
  // Zamboanga Peninsula
  "Western Mindanao State University",
  "Ateneo de Zamboanga University",
  "Zamboanga State College of Marine Sciences and Technology",
  "Jose Rizal Memorial State University",
  "Universidad de Zamboanga",
  // Northern Mindanao (Cagayan de Oro, Iligan, etc.)
  "Xavier University – Ateneo de Cagayan",
  "Mindanao State University – Iligan Institute of Technology",
  "Central Mindanao University",
  "University of Science and Technology of Southern Philippines",
  "Bukidnon State University",
  "Liceo de Cagayan University",
  "Capitol University",
  // Davao Region - KickSTART Mindanao venue
  "University of Mindanao",
  "Ateneo de Davao University",
  "University of the Philippines Mindanao",
  "University of Southeastern Philippines",
  "University of the Immaculate Conception",
  "San Pedro College",
  "Davao Doctors College",
  // Soccsksargen (General Santos, Koronadal, etc.)
  "Mindanao State University – General Santos",
  "University of Southern Mindanao",
  "Notre Dame of Dadiangas University",
  "Sultan Kudarat State University",
  "Cotabato Foundation College of Science and Technology",
  // Caraga
  "Caraga State University",
  "Father Saturnino Urios University",
  "Saint Paul University Surigao",
  "Surigao del Norte State University",
  "North Eastern Mindanao State University",
  // MIMAROPA
  "Palawan State University",
  "Western Philippines University",
  "Mindoro State University",
  "Romblon State University",
  "Marinduque State University",
  // Bangsamoro (BARMM)
  "Mindanao State University – Main",
  "Cotabato State University",
] as const;

export const OTHER_UNIVERSITY_LABEL = "Other (please specify)" as const;

// Island options (used for per-island slot limits)
export const ISLAND_OPTIONS = ["Luzon", "Visayas", "Mindanao"] as const;

// Course Dropdown Options
export const COURSE_OPTIONS = [
  "Bachelor in Mathematics Education",
  "Bachelor in Technology and Livelihood Education with Specialization in Information and Communications",
  "Bachelor of Library and Information Science",
  "BS Aeronautical Engineering",
  "BS Aerospace Engineering",
  "BS Agribusiness",
  "BS Agribusiness Management",
  "BS Agribusiness Management and Entrepreneurship",
  "BS Agricultural and Biosystems Engineering",
  "BS Agricultural Biotechnology",
  "BS Agricultural Chemistry",
  "BS Agricultural Economics",
  "BS Agricultural Engineering",
  "BS Agricultural Technology",
  "BS Agriculture",
  "BS Animal Husbandry",
  "BS Animal Science",
  "BS Applied Mathematics",
  "BS Applied Mathematics major in Mathematical Finance",
  "BS Applied Physics",
  "BS Applied Physics with Applied Computer System",
  "BS Applied Physics with Materials Science and Engineering",
  "BS Applied Statistics",
  "BS Architecture",
  "BS Astronomy",
  "BS Astronomy Technology",
  "BS Basic Medical Sciences6",
  "BS Biochemistry",
  "BS Biology",
  "BS Biology for Teachers",
  "BS Biotechnology",
  "BS Ceramics Engineering",
  "BS Chemical Engineering",
  "BS Chemistry",
  "BS Chemistry Major in Business",
  "BS Chemistry for Teachers",
  "BS Chemistry with Applied Computer Systems",
  "BS Chemistry with Materials Science and Engineering",
  "BS Civil Engineering",
  "BS Clothing Technology",
  "BS Community Nutrition",
  "BS Computer Engineering",
  "BS Computer Science",
  "BS Electrical Engineering",
  "BS Electronics and Communications Engineering",
  "BS Electronics Engineering",
  "BS Environmental Engineering",
  "BS Environmental Science",
  "BS Fine Arts Major in Industrial Design",
  "BS Fisheries",
  "BS Food Science and Technology",
  "BS Food Technology",
  "BS Forestry",
  "BS Geodetic Engineering",
  "BS Geography",
  "BS Geology",
  "BS Geothermal Engineering",
  "BS Health Science",
  "BS Human Biology5",
  "BS Industrial Design",
  "BS Industrial Engineering",
  "BS Industrial Management Engineering-Information Technology",
  "BS Industrial Pharmacy",
  "BS Information and Communications Technology",
  "BS Information System",
  "BS Information Technology",
  "BS Information Technology Systems",
  "BS Instrumentation and Control Engineering",
  "BS Life Sciences",
  "BS Management Information Systems",
  "BS Manufacturing Engineering",
  "BS Manufacturing Engineering-Management-Biomedical Engineering",
  "BS Manufacturing Engineering-Management-Mechatronics and Robotics",
  "BS Marine Biology",
  "BS Marine Science",
  "BS Materials Engineering",
  "BS Mathematics",
  "BS Mathematics and Science Teaching",
  "BS Mathematics for Teachers",
  "BS Mechanical Engineering",
  "BS Mechatronics Engineering",
  "BS Medical Laboratory Science",
  "BS Medical Technology",
  "BS Metallurgical Engineering",
  "BS Meteorology",
  "BS Microbiology",
  "BS Mining Engineering",
  "BS Molecular Biology and Biotechnology",
  "BS Nutrition",
  "BS Nutrition and Dietetics",
  "BS Packaging Engineering",
  "BS Petroleum Engineering",
  "BS Pharmaceutical Sciences",
  "BS Pharmacy (4-year program)",
  "BS Pharmacy major in Clinical Pharmacy (5-year program)",
  "BS Physics",
  "BS Physics for Teachers",
  "BS Psychology",
  "BS Public Health",
  "BS Speech Pathology",
  "BS Statistics",
  "BSE Biological Sciences",
  "BSE Biology",
  "BSE Biology-Chemistry",
  "BSE Chemistry",
  "BSE General Sciences",
  "BSE Mathematics",
  "BSE Physical Sciences",
  "BSE Physics",
  "BSE Physics-Chemistry",
  "BSE Physics-Mathematics",
  "BSE Science",
  "Doctor of Veterinary Medicine",
] as const;
