export const YEAR_LEVELS = [
  "1st year",
  "2nd year",
  "3rd year",
  "4th year",
  "5th year",
  "6th year",
] as const;
export const YEAR_AWARDED_OPTIONS = [
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
  "2025",
] as const;

export const SCHOLARSHIP_OPTIONS = [
  "UG RA 7687",
  "UG Merit",
  "JLSS RA 7687",
  "JLSS Merit",
  "JLSS RA 10612",
] as const;

// University Dropdown Options (kept in sync with client)
export const UNIVERSITY_OPTIONS = [
  "Adamson University",
  "Ateneo de Manila University",
  "Centro Escolar University",
  "De La Salle University – Manila",
  "Eulogio Rodriguez Institute of Science and Technology",
  "Far Eastern University – Manila",
  "Far Eastern University – Tech",
  "Far Eastern University – NRMF",
  "Mapúa University (Manila/Makati)",
  "National University – Manila",
  "New Era University",
  "Our Lady of Fatima University – Quezon City",
  "Our Lady of Fatima University – Valenzuela",
  "Philippine Normal University",
  "National Aviation Academy of the Philippines",
  "Polytechnic University of the Philippines – Manila",
  "Polytechnic University of the Philippines – Taguig",
  "Polytechnic University of the Philippines – Quezon City",
  "Pamantasan ng Lungsod ng Maynila",
  "Rizal Technological University – Mandaluyong",
  "Rizal Technological University – Pasig",
  "Technological Institute of the Philippines – Manila",
  "Technological Institute of the Philippines – Quezon City",
  "Technological University of the Philippines – Manila",
  "Technological University of the Philippines – Taguig",
  "Trinity University of Asia",
  "Marikina Polytechnic College",
  "Assumption College San Lorenzo",
  "PATTS College of Aeronautics",
  "Manila Central University (MCU)",
  "University of Santo Tomas",
  "University of the East – Manila",
  "University of the Philippines – Diliman",
  "University of the Philippines – Manila",
  "University of the Philippines",
  "Batangas State University",
  "Cavite State University",
  "Laguna State Polytechnic University",
  "University of Rizal System",
  "University of Batangas",
  "Lyceum of the Philippines University – Batangas",
  "De La Salle Lipa",
  "Southern Luzon State University",
  "Manuel S. Enverga University Foundation",
  "First Asia Institute of Technology and Humanities",
  "University of the Philippines Los Baños",
  "Central Luzon State University",
  "Bulacan State University",
  "Tarlac State University",
  "Don Honorio Ventura Technological State University",
  "Nueva Ecija University of Science and Technology",
  "Bataan Peninsula State University",
  "Pampanga State University",
  "Angeles University Foundation",
  "Holy Angel University",
  "University of the Assumption",
  "Bicol University",
  "Ateneo de Naga University",
  "University of Nueva Caceres",
  "Polytechnic State University of Bicol",
  "Central Bicol State University of Agriculture",
  "Mariano Marcos State University",
  "Pangasinan State University",
  "Cagayan State University",
  "Isabela State University",
  "University of Northern Philippines",
  "Nueva Vizcaya State University",
  "University of the Philippines Baguio",
  "Saint Louis University",
  "University of the Cordilleras",
  "Benguet State University",
  "University of Baguio",
  "University of the Philippines Visayas",
  "West Visayas State University",
  "Central Philippine University",
  "University of San Agustin",
  "University of Iloilo",
  "University of Saint La Salle",
  "Carlos Hilado Memorial State University",
  "Capiz State University",
  "Aklan State University",
  "University of Southern Philippines Foundation",
  "University of San Carlos",
  "Cebu Technological University",
  "Cebu Normal University",
  "Silliman University",
  "University of Cebu",
  "Cebu Doctor's University",
  "University of the Visayas",
  "Holy Name University",
  "Bohol Island State University",
  "Negros Oriental State University",
  "Eastern Visayas State University",
  "Leyte Normal University",
  "University of the Philippines Tacloban",
  "Visayas State University",
  "Samar State University",
  "Western Mindanao State University",
  "Ateneo de Zamboanga University",
  "Zamboanga State College of Marine Sciences and Technology",
  "Jose Rizal Memorial State University",
  "Universidad de Zamboanga",
  "Xavier University – Ateneo de Cagayan",
  "Mindanao State University – Iligan Institute of Technology",
  "Central Mindanao University",
  "University of Science and Technology of Southern Philippines",
  "Bukidnon State University",
  "Liceo de Cagayan University",
  "Capitol University",
  "University of Mindanao",
  "Ateneo de Davao University",
  "University of the Philippines Mindanao",
  "University of Southeastern Philippines",
  "University of the Immaculate Conception",
  "San Pedro College",
  "Davao Doctors College",
  "Mindanao State University – General Santos",
  "University of Southern Mindanao",
  "Notre Dame of Dadiangas University",
  "Sultan Kudarat State University",
  "Cotabato Foundation College of Science and Technology",
  "Caraga State University",
  "Father Saturnino Urios University",
  "Saint Paul University Surigao",
  "Surigao del Norte State University",
  "North Eastern Mindanao State University",
  "Palawan State University",
  "Western Philippines University",
  "Mindoro State University",
  "Romblon State University",
  "Marinduque State University",
  "Mindanao State University – Main",
  "Cotabato State University",
] as const;

export const OTHER_UNIVERSITY_LABEL = "Other (please specify)" as const;

// Island options
export const ISLAND_OPTIONS = ["Luzon", "Visayas", "Mindanao"] as const;